name: draft
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^9.0.0
  calendar_view: ^1.4.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  intl: ^0.20.2
  syncfusion_flutter_calendar: ^28.2.4
  table_calendar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
